"""Create table usersss

Revision ID: b05f6f25406f
Revises: 63e6de08915b
Create Date: 2026-01-06 17:12:41.197168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b05f6f25406f'
down_revision: Union[str, Sequence[str], None] = '63e6de08915b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'transactions', ['transaction_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='unique')
    # ### end Alembic commands ###
