"""Create table users

Revision ID: f6a4fb0ad122
Revises: b05f6f25406f
Create Date: 2026-01-06 17:15:49.213818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6a4fb0ad122'
down_revision: Union[str, Sequence[str], None] = 'b05f6f25406f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('votes_count', sa.Integer(), nullable=False))
    op.drop_column('transactions', 'amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('transactions', 'votes_count')
    # ### end Alembic commands ###
